name: Mac (BASH 3.2)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'bash --version | head -1'
        shell: bash
      - run: bin/spec spec/
        shell: bash
        env:
          VERBOSE: true