name: BASH 5.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bx-sh/setup-bx@master
      - run: 'bash --version | head -1'
        shell: bash
      - run: bin/spec spec/
        shell: bash
        env:
          VERBOSE: true