name: BASH 4.4

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: 'bash --version | head -1'
        shell: bash
      - run: bin/spec spec/
        shell: bash
        env:
          VERBOSE: true